changeLogFile=changelogs/master.xml
url=jdbc:mysql://localhost:3307/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
username=test_user
password=test_password
driver=com.mysql.cj.jdbc.Driver
logLevel=info
